vaadin.launch-browser=true
spring.application.name=water-billing

# H2 DATABASE (in-memory)
spring.datasource.url=jdbc:h2:mem:water_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

#Dummy data initialization
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# H2 CONSOLE (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA (let Hibernate create tables for now)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway (disable for H2 dev OR use it later)
spring.flyway.enabled=false

server.port=8082
