version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: db_micro_mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - mysql_micro_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  auth-service:
    build:
      context: .
      dockerfile: auth-service/Dockerfile
    container_name: auth_service
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - auth-service/.env
    environment:
      DB_URL: jdbc:mysql://db:3306/water_auth?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      JWT_SECRET: 849864a7cc912ad511ed4f19569c1dc3e1b4519bb81059882cea44f51787c7aa

  property-service:
    build:
      context: .
      dockerfile: property-service/Dockerfile
    container_name: property_service
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - property-service/.env
    environment:
      DB_URL: jdbc:mysql://db:3306/water_property?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      JWT_SECRET: 849864a7cc912ad511ed4f19569c1dc3e1b4519bb81059882cea44f51787c7aa

  waterconfig-service:
    build:
      context: .
      dockerfile: waterconfig-service/Dockerfile
    container_name: waterconfig_service
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - waterconfig-service/.env
    environment:
      DB_URL: jdbc:mysql://db:3306/water_config?createDatabaseIfNotExist=true
      DB_USERNAME: root
      DB_PASSWORD: rootpass
      JWT_SECRET: 849864a7cc912ad511ed4f19569c1dc3e1b4519bb81059882cea44f51787c7aa
      PROPERTY_SERVICE_URL: http://property-service:8082

volumes:
  mysql_micro_data:
