spring.application.name=reporting-service
spring.config.import=optional:file:.env[.properties]
server.port=8085

# JWT
jwt.secret=${JWT_SECRET}

# Actuator
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=never

# External Service Feign Client URLs
telemetry-service.url=${TELEMETRY_SERVICE_URL:http://localhost:8084}
auth-service.url=${AUTH_SERVICE_URL:http://localhost:8081}

# Eureka Registration
eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8089/eureka/}
