server:
  port: 8090

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:8091"
              - "http://localhost:8090"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: auth-service
          uri: ${AUTH_SERVICE_URL:lb://auth-service}
          predicates:
            - Path=/auth/**, /users/**
        - id: auth-service-v3
          uri: ${AUTH_SERVICE_URL:lb://auth-service}
          predicates:
            - Path=/auth-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: property-service
          uri: ${PROPERTY_SERVICE_URL:lb://property-service}
          predicates:
            - Path=/apartments/**, /apartment-types/**, /blocks/**
        - id: property-service-v3
          uri: ${PROPERTY_SERVICE_URL:lb://property-service}
          predicates:
            - Path=/property-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: waterconfig-service
          uri: ${WATERCONFIG_SERVICE_URL:lb://waterconfig-service}
          predicates:
            - Path=/water-sources/**, /water-rates/**, /apartment-source-configs/**
        - id: waterconfig-service-v3
          uri: ${WATERCONFIG_SERVICE_URL:lb://waterconfig-service}
          predicates:
            - Path=/waterconfig-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: telemetry-service
          uri: ${TELEMETRY_SERVICE_URL:lb://telemetry-service}
          predicates:
            - Path=/daily-logs/**
        - id: telemetry-service-v3
          uri: ${TELEMETRY_SERVICE_URL:lb://telemetry-service}
          predicates:
            - Path=/telemetry-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

        - id: reporting-service
          uri: ${REPORTING_SERVICE_URL:lb://reporting-service}
          predicates:
            - Path=/dashboard/**, /monthly-summary/**
        - id: reporting-service-v3
          uri: ${REPORTING_SERVICE_URL:lb://reporting-service}
          predicates:
            - Path=/reporting-service/v3/api-docs
          filters:
            - SetPath=/v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: 1. Auth Service
        url: /auth-service/v3/api-docs
      - name: 2. Property Service
        url: /property-service/v3/api-docs
      - name: 3. Water Config Service
        url: /waterconfig-service/v3/api-docs
      - name: 4. Telemetry Service
        url: /telemetry-service/v3/api-docs
      - name: 5. Reporting Service
        url: /reporting-service/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8089/eureka/}

jwt:
  secret: ${JWT_SECRET:849864a7cc912ad511ed4f19569c1dc3e1b4519bb81059882cea44f51787c7aa}

